# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('licen_number', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('licaen_type', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('pan_card_pic', models.ImageField(default='no_image.png', upload_to='driver_pic')),
                ('adhar_card', models.ImageField(default='no_image.png', upload_to='driver_pic')),
                ('reference_one', models.CharField(max_length=100)),
                ('reference_two', models.CharField(max_length=100)),
                ('address_one', models.CharField(max_length=100)),
                ('address_two', models.CharField(max_length=100)),
                ('pair_status', models.BooleanField(default=False)),
                ('pair_with', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
