# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_add',
            name='ref_moblie_one',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver_add',
            name='ref_moblie_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
