# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-25 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licanse_number', models.CharField(max_length=100)),
                ('licanse_image', models.ImageField(default='no_image.png', upload_to='truck_info')),
                ('roc_image', models.ImageField(default='no_image.png', upload_to='truck_info')),
                ('truck_oem', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('wheels', models.CharField(max_length=100)),
                ('axle_type', models.CharField(max_length=100)),
                ('truck_type', models.CharField(max_length=100)),
                ('truck_capacity', models.CharField(max_length=100)),
                ('truck_lemgth', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('owener_name', models.CharField(max_length=100)),
                ('conatact', models.CharField(max_length=100)),
                ('pan_card', models.CharField(max_length=100)),
                ('date_of_fitnace_certificate', models.DateField(blank=True, null=True)),
                ('pan_card_pic', models.ImageField(default='no_image.png', upload_to='truck_info')),
                ('fitness_certificate', models.ImageField(default='no_image.png', upload_to='truck_info')),
                ('pair_status', models.BooleanField(default=False)),
            ],
        ),
    ]
