# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair_and_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty_status', models.BooleanField(default=False)),
                ('maintaion_status', models.BooleanField(default=False)),
                ('break_down_status', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='truckdriverpair_pair_and_status_related', to='driver.Driver_add')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='truckdriverpair_pair_and_status_related', to='truck.Truck_data')),
            ],
        ),
    ]
