# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckDriverPair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair_and_status',
            name='shipment_status',
            field=models.BooleanField(default=False),
        ),
    ]
