# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truckDriverPair', '0002_pair_and_status_shipment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment_ids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=100)),
                ('pair_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='truckdriverpair_shipment_ids_related', to='truckDriverPair.Pair_and_status')),
            ],
        ),
    ]
