# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aproved_mobile_number',
            name='activation_status',
            field=models.BooleanField(default=True),
        ),
    ]
