# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-25 02:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(default='no_image.png', upload_to='profile_pic')),
                ('pan_card', models.ImageField(default='no_image.png', upload_to='profile_pic')),
                ('address', models.CharField(max_length=1000)),
                ('landline_number', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=1000)),
                ('designation', models.CharField(max_length=1000)),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
