# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-25 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_user',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
