# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-25 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170625_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='add_user',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='add_user',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='add_user',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='add_user',
            name='landline_number',
        ),
        migrations.RemoveField(
            model_name='add_user',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='add_user',
            name='password',
        ),
    ]
