# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-25 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170625_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_user',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='add_user',
            name='company_logo',
            field=models.ImageField(default='no_image.png', upload_to='profile_pic'),
        ),
        migrations.AddField(
            model_name='add_user',
            name='contact_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='add_user',
            name='designation',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='add_user',
            name='landline_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_user',
            name='pan_card',
            field=models.ImageField(default='no_image.png', upload_to='profile_pic'),
        ),
    ]
