# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20170625_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='password_reset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emil', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=100)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
